#pragma once

#include "CoreMinimal.h"
#include "NoGrassConfiguration.h"
#include "Subsystems/WorldSubsystem.h"
#include "Tickable.h"
#include "NoGrassWorldSubsystem.generated.h"

class AFGBuildable;
class AFGBuildableSubsystem;
class AFGLightweightBuildableSubsystem;
class AFGFoliageRemovalSubsystem;
class AFGCliffActor;
class ANoGrassPermanentState;
class UGrassInstancedStaticMeshComponent;
class UHierarchicalInstancedStaticMeshComponent;
class UStaticMesh;
struct FClusterNode;
struct FNoGrassGeneratedGrassBufferSnapshot;
class FStaticMeshInstanceData;

struct FNoGrassLightweightOwnerKey
{
	TWeakObjectPtr<AFGLightweightBuildableSubsystem> Subsystem;
	TObjectPtr<UClass> BuildableClass = nullptr;
	int32 RuntimeIndex = INDEX_NONE;

	bool operator==(const FNoGrassLightweightOwnerKey& Other) const
	{
		return Subsystem == Other.Subsystem &&
			BuildableClass == Other.BuildableClass &&
			RuntimeIndex == Other.RuntimeIndex;
	}

	friend uint32 GetTypeHash(const FNoGrassLightweightOwnerKey& Key)
	{
		return HashCombineFast(
			HashCombineFast(GetTypeHash(Key.Subsystem), GetTypeHash(Key.BuildableClass)),
			GetTypeHash(Key.RuntimeIndex));
	}
};

struct FNoGrassInstanceKey
{
	TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent> Component;
	FIntVector QuantizedLocation = FIntVector::ZeroValue;

	bool operator==(const FNoGrassInstanceKey& Other) const
	{
		return Component == Other.Component && QuantizedLocation == Other.QuantizedLocation;
	}

	friend uint32 GetTypeHash(const FNoGrassInstanceKey& Key)
	{
		return HashCombineFast(GetTypeHash(Key.Component), GetTypeHash(Key.QuantizedLocation));
	}
};

struct FNoGrassCoverageVolume
{
	FTransform LocalToWorld = FTransform::Identity;
	FBox LocalBounds = FBox(ForceInit);
	FBox WorldBounds = FBox(ForceInit);
	bool bLandscapeOnly = false;
};

struct FNoGrassCandidateBatch
{
	TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent> Component;
	TArray<int32> InstanceIndices;
	int32 Cursor = 0;
};

struct FNoGrassCoverageTask
{
	uint64 OwnerId = 0;
	FNoGrassCoverageVolume Volume;
	FVector QueryCenter = FVector::ZeroVector;
	float QueryRadius = 0.0f;
	bool bCandidatesGathered = false;
	TArray<FNoGrassInstanceKey> SuppressedCandidates;
	int32 SuppressedCandidateCursor = 0;
	TArray<FNoGrassCandidateBatch> CandidateBatches;
	int32 BatchCursor = 0;
};

struct FNoGrassOwnerState
{
	TSet<FNoGrassInstanceKey> GrassInstances;
	TArray<FNoGrassCoverageVolume> CoverageVolumes;
	double LastCoverageQueuedAt = -DBL_MAX;
};

struct FNoGrassRegrowthWave
{
	FVector2D Origin = FVector2D::ZeroVector;
	FVector2D AxisX = FVector2D(1.0, 0.0);
	FVector2D AxisY = FVector2D(0.0, 1.0);
	FVector2D Min = FVector2D::ZeroVector;
	FVector2D Max = FVector2D::ZeroVector;
	bool bValid = false;
};

struct FNoGrassPendingOwnerRelease
{
	uint64 OwnerId = 0;
	FNoGrassOwnerState OwnerState;
};

struct FNoGrassCliffRegrowthVolume
{
	FNoGrassCoverageVolume Volume;
	FNoGrassRegrowthWave Wave;
	double RestoreStartAt = 0.0;
	double RestoreEndAt = 0.0;
	double NextVisualRefreshAt = 0.0;
};

struct FNoGrassSuppressionState
{
	FTransform OriginalWorldTransform = FTransform::Identity;
	int32 LastKnownInstanceIndex = INDEX_NONE;
	TSet<uint64> Owners;
	bool bUsePhysicalRemoval = false;
	bool bPendingPhysicalRemoval = false;
	bool bPhysicallyRemoved = false;
};

struct FNoGrassRestoreEntry
{
	FNoGrassInstanceKey Key;
	double RestoreAt = 0.0;
	float RestoreAlpha = -1.0f;
};

UCLASS(Transient)
class NOGRASSUNDERBUILDINGS_API UNoGrassWorldSubsystem final : public UTickableWorldSubsystem
{
	GENERATED_BODY()

public:
	virtual bool ShouldCreateSubsystem(UObject* Outer) const override;
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;
	virtual void Deinitialize() override;
	virtual void Tick(float DeltaTime) override;
	virtual TStatId GetStatId() const override;
	virtual bool IsTickable() const override;

	void HandleLightweightAdded(
		AFGLightweightBuildableSubsystem* LightweightSubsystem,
		TSubclassOf<AFGBuildable> BuildableClass,
		int32 RuntimeIndex,
		bool bFromSaveData = false,
		AActor* BuildEffectInstigator = nullptr);

	void HandleActorPlaced(AFGBuildable* Buildable, AActor* BuildEffectInstigator);

	void HandleLightweightRemoved(
		AFGLightweightBuildableSubsystem* LightweightSubsystem,
		TSubclassOf<AFGBuildable> BuildableClass,
		int32 RuntimeIndex);

	void AppendCoverageDiagnostics(
		const FVector& ScanCenter,
		float ScanRadius,
		TArray<FString>& OutLines) const;
	FString GetRegrowthStatus() const;

	/**
	 * Filters render-only grass buffers generated by Landscape Grass and
	 * AFGCliffActor. These buffers have no editable CPU-side HISM instances, so
	 * they are updated in place without invalidating Unreal's landscape cache.
	 */
	int32 FilterGeneratedGrass(
		UGrassInstancedStaticMeshComponent* Component,
		TArray<FClusterNode>& ClusterTree,
		int32& OcclusionLayerNum,
		int32& NumBuiltRenderInstances,
		FStaticMeshInstanceData* InstanceData);

private:
	UFUNCTION()
	void HandleBuildableAdded(AFGBuildable* Buildable);

	UFUNCTION()
	void HandleBuildableRemoved(AFGBuildable* Buildable);

	void TryBindBuildableSubsystem();
	void StartRegionalScan(const FVector& ScanOrigin);
	void ProcessActorScan(double Deadline);
	void ProcessLightweightScan(double Deadline);
	void ProcessCoverageTasks(double Deadline);
	void ProcessRestores(double Deadline);
	void ProcessGeneratedGrassRegrowthAndRefresh(double Deadline);
	void FlushPendingOwnerReleases();
	void FlushPendingPhysicalRemovals();
	void FlushDirtyComponents();
	void RefreshLandscapeGrassReach();
	void RebasePendingRestores(
		double Now,
		double NewMinimumDelay,
		double NewMaximumDelay);
	void ScheduleGeneratedGrassRefresh(
		const TArray<FNoGrassCoverageVolume>& Volumes,
		double DelaySeconds = 0.25);
	int32 FilterGeneratedGrassBuffer(
		UGrassInstancedStaticMeshComponent* Component,
		FStaticMeshInstanceData* InstanceData,
		TArray<FClusterNode>& ClusterTree,
		int32& OcclusionLayerNum,
		int32& NumBuiltRenderInstances);

	void QueueActorCoverage(AFGBuildable* Buildable, bool bForce = false);
	void QueueLightweightCoverage(
		AFGLightweightBuildableSubsystem* LightweightSubsystem,
		TSubclassOf<AFGBuildable> BuildableClass,
		int32 RuntimeIndex,
		bool bForce = false);
	uint64 FindOrAddActorOwner(AFGBuildable* Buildable);
	uint64 FindOrAddLightweightOwner(const FNoGrassLightweightOwnerKey& Key);
	void ReleaseOwner(uint64 OwnerId);

	void BuildCoverageForActor(AFGBuildable* Buildable, TArray<FNoGrassCoverageVolume>& OutVolumes) const;
	void BuildCoverageForLightweight(
		AFGLightweightBuildableSubsystem* LightweightSubsystem,
		TSubclassOf<AFGBuildable> BuildableClass,
		int32 RuntimeIndex,
		TArray<FNoGrassCoverageVolume>& OutVolumes) const;
	void AppendMeshCoverage(
		UStaticMesh* StaticMesh,
		const FTransform& MeshToWorld,
		TArray<FNoGrassCoverageVolume>& OutVolumes) const;
	void AddCoverageVolume(
		const FTransform& LocalToWorld,
		const FBox& LocalBounds,
		TArray<FNoGrassCoverageVolume>& OutVolumes,
		bool bLandscapeOnly = false) const;
	void QueueCoverageVolume(
		uint64 OwnerId,
		const FNoGrassCoverageVolume& Volume);
	void AddPermanentGrassCoverage(
		const TArray<FNoGrassCoverageVolume>& Volumes);
	void TryBindPermanentState();
	void RefreshPermanentCoverage();
	void ApplyConfiguration();

	bool IsDecorativeGrass(
		UHierarchicalInstancedStaticMeshComponent* Component) const;
	bool GrassIntersectsVolume(
		const FTransform& GrassWorldTransform,
		UStaticMesh* GrassMesh,
		const FNoGrassCoverageVolume& Volume) const;
	void SuppressGrass(
		uint64 OwnerId,
		UHierarchicalInstancedStaticMeshComponent* Component,
		int32 InstanceIndex);
	int32 ResolveInstanceIndex(
		const FNoGrassInstanceKey& Key,
		const FNoGrassSuppressionState& State) const;
	void GatherSuppressedCandidates(FNoGrassCoverageTask& Task) const;
	void AddSuppressedToSpatialGrid(const FNoGrassInstanceKey& Key);
	void RemoveSuppressedFromSpatialGrid(const FNoGrassInstanceKey& Key);

	static FIntVector QuantizeLocation(const FVector& Location);
	static FIntPoint SpatialCellForLocation(const FVector& Location);
	static bool SegmentIntersectsBox(const FVector& Start, const FVector& End, const FBox& Box);

private:
	TWeakObjectPtr<AFGBuildableSubsystem> BuildableSubsystem;
	TWeakObjectPtr<AFGLightweightBuildableSubsystem> LightweightSubsystem;

	TMap<TWeakObjectPtr<AFGBuildable>, uint64> ActorOwners;
	TMap<FNoGrassLightweightOwnerKey, uint64> LightweightOwners;
	TMap<uint64, FNoGrassOwnerState> OwnerStates;
	TMap<FNoGrassInstanceKey, FNoGrassSuppressionState> SuppressedGrass;
	TMap<FIntPoint, TSet<FNoGrassInstanceKey>> SuppressedSpatialGrid;

	TQueue<TSharedPtr<FNoGrassCoverageTask, ESPMode::NotThreadSafe>> CoverageQueue;
	TSharedPtr<FNoGrassCoverageTask, ESPMode::NotThreadSafe> ActiveCoverageTask;
	TArray<FNoGrassRestoreEntry> RestoreQueue;
	bool bRestoreQueueDirty = false;
	TArray<FNoGrassPendingOwnerRelease> PendingOwnerReleases;
	double LastPendingOwnerReleaseAt = -DBL_MAX;
	TArray<FNoGrassCliffRegrowthVolume> CliffRegrowthVolumes;
	TMap<
		TWeakObjectPtr<UGrassInstancedStaticMeshComponent>,
		TSharedPtr<FNoGrassGeneratedGrassBufferSnapshot>> GeneratedGrassBufferSnapshots;
	FBox PendingGeneratedGrassRefreshBounds = FBox(ForceInit);
	double NextGeneratedGrassRefreshAt = DBL_MAX;
	bool bApplyingGeneratedGrassBufferSnapshot = false;

	TWeakObjectPtr<ANoGrassPermanentState> PermanentState;
	TArray<FNoGrassCoverageVolume> PermanentCoverageVolumes;
	TMap<FIntPoint, TArray<int32>> PermanentCoverageSpatialGrid;
	int32 LastPermanentVolumeCount = INDEX_NONE;
	double PermanentCoverageRefreshAt = DBL_MAX;

	TArray<TWeakObjectPtr<AFGBuildable>> ActorScanBuildables;
	int32 ActorScanCursor = 0;
	bool bActorScanActive = false;
	TArray<TSubclassOf<AFGBuildable>> LightweightScanClasses;
	int32 LightweightScanClassCursor = 0;
	int32 LightweightScanInstanceCursor = 0;
	bool bLightweightScanActive = false;
	FVector ActiveScanOrigin = FVector::ZeroVector;

	TSet<TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent>> DirtyComponents;
	TSet<TWeakObjectPtr<UHierarchicalInstancedStaticMeshComponent>>
		PendingPhysicalRemovalComponents;
	mutable TSet<FName> LoggedGrassMeshes;

	uint64 NextOwnerId = 1;
	double NextRegionalScanAt = 0.0;
	double NextLandscapeReachScanAt = 0.0;
	double NextConfigurationRefreshAt = 0.0;
	double PermanentStateSpawnAfter = 1.0;
	double LastObservedRegrowthSeconds = 600.0;
	double LastObservedRegrowthMaxSeconds = 900.0;
	bool LastObservedGradualRegrowth = true;
	float LastObservedCliffGrassPadding = 100.0f;
	float EffectiveLandscapePadding = 200.0f;
	float EffectiveLandscapeVerticalPadding = 200.0f;
	FVector LastRegionalScanOrigin = FVector(UE_BIG_NUMBER);
	bool bShuttingDown = false;
};
